[package]
name = "pp-bindings"
version = "0.1.0"
edition = "2018"

[lib]
name = "pp_bindings"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.7"
features = ["extension-module"]

[dependencies.rosu-pp]
version = "0.3"
default_features = true